<?php

use Drupal\entity_comparison\Entity\EntityComparison;

function digitalia_muni_compare_tweaks_page_attachments(array &$attachements)
{
	$comparisons = EntityComparison::loadMultiple();

	$settings = array();
	$groups_enabled = \Drupal::service("module_handler")->moduleExists("compare_metaplatform"); 

	foreach ($comparisons as $id => $entity_comparison) {
		$identifier = "no_groups";
		if ($groups_enabled) {
			$identifier = $entity_comparison->getGroupName();
		}

		$settings['groups_enabled'] = $groups_enabled;
		$settings[$identifier]['block_selector'] = "#block-islandora-muni-" . str_replace('_', '', $id);
		$settings[$identifier]['text_selector'] = ".content a.entity-comparison-" . str_replace('_', '-', $id);
		$settings[$identifier]['comparison_url_snippet'] = str_replace('_', '-', $id);
	}

	\Drupal::logger("DEBUG_COMPARE_TRUE")->debug(true);
	\Drupal::logger("DEBUG_COMPARE_FALSE")->debug(false);
	\Drupal::logger("DEBUG_COMPARE")->debug($groups_enabled);
	\Drupal::logger("DEBUG_COMPARE")->debug(print_r($settings, TRUE));

	$attachements['#attached']['library'][] = 'digitalia_muni_compare_tweaks/dynamic_compare';
	$attachements['#attached']['drupalSettings']['digitaliaMuniCompareTweaks']['dynamicCompare'] = $settings;
}

